# Generated by Django 5.1.2 on 2024-10-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
