# Generated by Django 5.1.2 on 2024-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_padre', models.CharField(max_length=50)),
                ('fecha_nac_padre', models.DateField()),
                ('nombre_madre', models.CharField(max_length=50)),
                ('fecha_nac_madre', models.DateField()),
                ('convivientes', models.CharField(max_length=50)),
                ('total_hermanos', models.IntegerField()),
                ('posicion_familiar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotasAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('fecha_nota', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('estado_aprobacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'temp_user',
            },
        ),
    ]
