# Generated by Django 5.1.2 on 2024-10-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_sede_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='coordinador',
        ),
    ]
