# Generated by Django 5.1.2 on 2024-11-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_remove_sede_coordinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentesfamiliares',
            name='alumno',
        ),
    ]
