# Generated by Django 5.1.2 on 2024-11-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_remove_antecedentesfamiliares_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentesfamiliares',
            name='cantidad_personas_hogar',
            field=models.IntegerField(null=True),
        ),
    ]
