# Generated by Django 5.1.2 on 2024-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprogramaapoyo',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
