# Generated by Django 5.1.2 on 2024-10-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('administrativo', '0002_initial'),
        ('personas', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.apoderado'),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='docente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='docente',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.sede'),
        ),
    ]
