# Generated by Django 5.1.2 on 2024-10-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='region',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='region',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='region',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='region',
        ),
    ]
