# Generated by Django 5.1.2 on 2024-10-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_alumno_comuna_remove_alumno_region_and_more'),
        ('registro', '0004_coordinadorsede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='alumno',
            name='comuna',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apoderado',
            name='comuna',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinador',
            name='comuna',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='comuna',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='registro.comuna'),
            preserve_default=False,
        ),
    ]
