# Generated by Django 5.1.2 on 2024-10-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_remove_alumno_ciudad_remove_apoderado_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='apoderado',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='comuna',
        ),
    ]
