# Generated by Django 5.1.2 on 2024-10-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_remove_alumno_comuna_remove_apoderado_comuna_and_more'),
        ('registro', '0004_coordinadorsede'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.comuna'),
        ),
        migrations.AddField(
            model_name='docente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.comuna'),
        ),
    ]
