# Generated by Django 5.1.2 on 2024-11-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alumno_comuna_apoderado_comuna_coordinador_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
