# Generated by Django 5.1.2 on 2024-11-20 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_alumno_antecedentes_familiares'),
        ('registro', '0010_remove_listahorariobloque_dia_bloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('parentezco', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.comuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado_backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoderado_backup', to='personas.apoderado_backup'),
        ),
    ]
