# Generated by Django 5.1.2 on 2024-10-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaHorarioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.IntegerField()),
                ('hr_inicio_programado', models.TimeField()),
                ('hr_termino_programado', models.TimeField()),
            ],
        ),
    ]
