# Generated by Django 5.1.2 on 2024-10-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_listahorariobloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.region'),
        ),
    ]
