# Generated by Django 5.1.2 on 2024-10-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_remove_sede_coordinador'),
        ('personas', '0003_remove_alumno_comuna_remove_alumno_region_and_more'),
        ('registro', '0003_comuna_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.coordinador')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.sede')),
            ],
        ),
    ]
