# Generated by Django 5.1.2 on 2024-10-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_coordinadorsede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroclase',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='registroclase',
            name='docente',
        ),
    ]
