# Generated by Django 5.1.2 on 2024-10-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_registroclase_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroclase',
            name='hr_inicio_efectivo',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroclase',
            name='hr_termino_efectivo',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroclase',
            name='registro_asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.registroasignatura'),
        ),
    ]
