# Generated by Django 5.1.2 on 2024-10-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_registroclase_hr_inicio_efectivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroclase',
            name='hr_inicio_efectivo',
        ),
        migrations.RemoveField(
            model_name='registroclase',
            name='hr_termino_efectivo',
        ),
        migrations.RemoveField(
            model_name='registroclase',
            name='registro_asignatura',
        ),
    ]
