# Generated by Django 5.1.2 on 2024-10-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_registroclase_hr_inicio_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listahorariobloque',
            name='dia',
            field=models.CharField(default='lunes', max_length=20),
            preserve_default=False,
        ),
    ]
