# Generated by Django 5.1.2 on 2024-10-31 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_listahorariobloque_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listahorariobloque',
            name='dia',
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('lista_horario_bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.listahorariobloque')),
                ('registro_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.registroasignatura')),
            ],
        ),
    ]
